# Generated by Django 5.0.7 on 2024-07-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustommodel',
            old_name='email_address',
            new_name='email',
        ),
    ]
