# Generated by Django 5.0.7 on 2024-08-02 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft')], default='DR', max_length=10, verbose_name='Status')),
                ('category', models.CharField(choices=[('Car', 'Car'), ('Computer', 'Computer'), ('Laptop', 'Laptop'), ('Phone', 'Phone'), ('House', 'House'), ('Other', 'Other')], default='Other', max_length=10, verbose_name='Category')),
                ('title', models.CharField(default='title product', max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('low_description', models.TextField(blank=True, default='product description', null=True, verbose_name='Description (low)')),
                ('full_description', models.TextField(blank=True, default='product full description', null=True, verbose_name='Description (full)')),
                ('product_image_cover', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Image product cover')),
                ('product_images', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/', verbose_name='Images product')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-price'],
            },
        ),
    ]
